# TODO: check if port 8080 is open
---
- name: Deploy cassandra
  hosts: cassandra_nodes
  become: true
  vars:
    cassandra_home: "/var/lib/cassandra"
    alloy_log_level: "warn"
    loki_url: "http://192.168.70.1:3100"
    mimir_url: "http://192.168.70.1:9009"
    cassandra_prometheus_port: 8080
  tasks:
    - name: Add repository
      ansible.builtin.yum_repository:
        name: grafana
        description: "Grafana repository"
        baseurl: https://rpm.grafana.com
        gpgcheck: true
        enabled: true
        gpgkey: https://rpm.grafana.com/gpg.key
    - name: Ensure alloy is installed
      ansible.builtin.dnf:
        name: alloy
        state: present
    - name: Grant alloy user access to logs
      ansible.builtin.command: "setfacl -R -m u:alloy:rX /var/log"
    - name: Copy template configuration
      ansible.builtin.template:
        src: config.alloy.j2
        dest: "/etc/alloy/config.alloy"
        mode: 0644
    - name: Reload services
      ansible.builtin.systemd:
        name: "alloy.service"
        enabled: true
        state: "restarted"
        daemon_reload: true
